stages:

  ingest:
    cmd: python src/data_ingestion.py
      --input data/raw/US_Accidents_March23.csv
      --output data/interim/ingested.csv
    deps:
      - src/data_ingestion.py
      - data/raw/US_Accidents_March23.csv
    outs:
      - data/interim/ingested.csv

  preprocess:
    cmd: python src/preprocessing.py
      --input data/interim/ingested.csv
      --output data/interim/preprocessed.csv
    deps:
      - src/preprocessing.py
      - data/interim/ingested.csv
    outs:
      - data/interim/preprocessed.csv
